version: "3.9"

services:
  server-baseline:
    build:
      context: ..
      dockerfile: docker/Dockerfile.baseline
    image: my-baseline-server:latest
    container_name: server-baseline

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    environment:
      - MODEL_NAME=resnet_baseline

    ports:
      - "8000:8000"   # FastAPI HTTP port

    volumes:
      - ../weight:/app/weight

  server-onnx-triton:
    build:
      context: ..
      dockerfile: docker/Dockerfile.triton
    image: my-triton-server:latest
    container_name: server-onnx-triton

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    environment:
      - MODEL_NAME=resnet_onnx
      - TRITON_URL=localhost:8001

    ports:
      - "8000:8000"   # FastAPI HTTP port
      - "8001:8001"   # gRPC port
      - "8002:8002"   # Metrics port

    volumes:
      - ../model_repository:/models
 
  server-trt-triton:
    build:
      context: ..
      dockerfile: docker/Dockerfile.triton
    image: my-triton-server:latest
    container_name: server-trt-triton

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    environment:
      - MODEL_NAME=resnet_trt_int8_auto_config
      - TRITON_URL=localhost:8001

    ports:
      - "8000:8000"   # FastAPI HTTP port
      - "8001:8001"   # gRPC port
      - "8002:8002"   # Metrics port

    volumes:
      - ../model_repository:/models

